# Practical_6: Numpy

In [1]:
import numpy as np

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

In [2]:
# Exercise 1
a = np.arange(1,11)
print(a)



[ 1  2  3  4  5  6  7  8  9 10]


---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [3]:
b = np.zeros((3,3)) 
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

In [4]:
c = np.linspace(0,5,10)
print(c)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

In [5]:
d = np.eye(5)         # Create a 5x5 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

In [6]:
d = np.random.random((4,4))         
print(d)              

[[0.6980523  0.1094851  0.97892203 0.50206202]
 [0.35100812 0.40539129 0.19464397 0.10187881]
 [0.18919807 0.83747209 0.77093856 0.41402756]
 [0.64290666 0.52973779 0.3104256  0.849948  ]]


In [7]:
np.random.seed(0)         

---

### Exercise 6:
Find the shape of a NumPy array.

In [8]:
e = np.array([[1,2,3],[4,5,6]])  
print(b.shape)                   


(3, 3)


---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [9]:
k=np.arange(16)
k.shape=(4,4)
print(k)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


---

### Exercise 8:
Find the data type of the elements in a NumPy array.

In [10]:
print(k.dtype)

int64


---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [11]:
A= np.arange(2,101,2)
A

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

In [12]:
z=np.random.randint(10, 50,(6,6))
z

array([[10, 13, 13, 49, 19, 29],
       [31, 46, 33, 16, 34, 34],
       [22, 11, 48, 49, 33, 34],
       [27, 47, 35, 23, 18, 19],
       [30, 26, 15, 25, 10, 28],
       [45, 34, 39, 29, 29, 24]])

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

In [13]:

x = np.array([[1,2],[3,4]])

print(np.sum(x)) 

10


---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

In [14]:
p=np.mean([[1,2],[3,4]])
p

2.5

---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

In [15]:
A= np.max([2,7,11])
C=np.min([2,7,11])
print(A)
print(C)



11
2


---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

In [16]:
C=np.arange(20)
d=np.argmax(c)
print(d)


9


---

### Exercise 16:
Create a NumPy array and reverse its elements.

In [17]:
x=np.array([1,2,3,4])
reverse_x=x[::-1]
print(reverse_x)

[4 3 2 1]


### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [18]:
x = np.array([[20,10,15],[2,1,9],[3,40,18]])
y = np.array([[11,12,14],[16,18,30],[7,3,2]])

print(x*y)

[[220 120 210]
 [ 32  18 270]
 [ 21 120  36]]


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

In [19]:
a = np.arange(10)
print(np.diag(a))

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]


---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

In [20]:
x = np.array([[20,10,15],[2,1,9],[3,40,18]])
y = np.array([[11,12,14],[16,18,30],[7,3,2]])
print(x.dot(y))

[[ 485  465  610]
 [ 101   69   76]
 [ 799  810 1278]]


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

In [21]:
x=np.array([[1,2,3,4],[5,6,7,8]])
y=x.flatten()
print(y)

[1 2 3 4 5 6 7 8]


---

### Exercise 21:
Stack two NumPy arrays vertically.

In [22]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8,9],[10,11,12]])
z=np.vstack((x,y))
print(z)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


---

### Exercise 22:
Stack two NumPy arrays horizontally.

In [23]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8,9],[10,11,12]])
z=np.hstack((x,y))
print(z)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### Exercise 25:
Find the unique elements of a NumPy array.


In [24]:
x=np.array([1,2,9,8,2,5,9,7,6,4,2,1])
y=np.unique(x)
print(y)

[1 2 4 5 6 7 8 9]
